### ISSUE TITLE
DefaultRepository CreateAsync uses Newtonsoft JsonConvert.SerializeObject in TryLogDebugDetails which causes problems on some items.

### ISSUE THREAD

**Issue by cardgeny** [IEvangelist/azure-cosmos-dotnet-repository#460]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.CosmosRepository).

**Describe the bug**
When in debug mode TryLogDebugDetails in CreateAsync fails with 
`Self referencing loop detected for property 'Root' with type 'System.Text.Json.Nodes.JsonValuePrimitive`1[System.Text.Json.JsonElement]'. Path 'Messages[7].ToolCalls[0].Function.Arguments'.` 
error. If LogLevel is raised to 'Information' that error does not occur.

**To Reproduce**
- Replace default serializer with System.Text.Json.
- Try to CreateAsync item that works fine when not in debug mode

**Expected behavior**
- Either attempt to serialise and swallow exceptions
- Or set  Newtonsoft JsonConvert.SerializeObject to ignore self reference errors
- Or use the same serialiser as used for TItem

**Actual behavior**
Unhandled exception

**Environment summary**
SDK Version: 8.0.303
OS Version (e.g. Windows, Linux, MacOSX): Windows 11

**Additional context**
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Microsoft.Azure.CosmosRepository.DefaultRepository`1.TryLogDebugDetails(ILogger logger, Func`1 getMessage)
   at Microsoft.Azure.CosmosRepository.DefaultRepository`1.<CreateAsync>d__7.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()

**Comment by IEvangelist** [comment]
What does the code look like, could you share a small project that only includes the code that reproduces the bug? That's usually the best approach for addressing these types of concerns.

**Comment by cardgeny** [comment]
You're of course correct that it wouldn't happen in production. However it's a bit annoying having to bump up debug level during development.

Attached is a small repro sample with chopped down models. Effectively it's a one of OpenAI response messages that causes the problem.

[bug-repro.zip](https://github.com/user-attachments/files/16184519/bug-repro.zip)

**Comment by mateuszkumpf** [comment]
@cardgeny In your example, it is not the serialiser that is the problem but the model you are saving to the database, it is the model that contains the properties that have references to themselves. In this case, it would actually be possible to solve this problem by using ReferenceLoopHandling.Ignore in settings of serializer in CreateAsync and UpdateAsync.
@IEvangelist What do you think about that?

**Comment by cardgeny** [comment]
@mateuszkumpf Sure, it is the data that causes the serialiser to crash. At the same time the item is created in cosmos db just fine. I mean what harm would it be to use it with ReferenceLoopHandling.Ignore option as it doesn't handle such cases anyway?

**Comment by IEvangelist** [comment]
> @mateuszkumpf Sure, it is the data that causes the serialiser to crash. At the same time the item is created in cosmos db just fine. I mean what harm would it be to use it with ReferenceLoopHandling.Ignore option as it doesn't handle such cases anyway?

I'm fine with that, as long as it's isolated to that call.
