### ISSUE TITLE
Microsoft.Azure.Cosmos.ContainerProperties.set_UniqueKeyPolicy(UniqueKeyPolicy value) (version 2.1.8)

### ISSUE THREAD

**Issue by anujrhicstech** [IEvangelist/azure-cosmos-dotnet-repository#49]
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Microsoft.Azure.Cosmos.ContainerProperties.set_UniqueKeyPolicy(UniqueKeyPolicy value)
   at Microsoft.Azure.CosmosRepository.Providers.DefaultCosmosContainerProvider`1.GetContainerValueFactoryAsync()
   at Microsoft.Azure.CosmosRepository.Providers.DefaultCosmosContainerProvider`1.<.ctor>b__7_0()
   at Microsoft.Azure.CosmosRepository.DefaultRepository`1.GetAsync(String id, PartitionKey partitionKey, CancellationToken cancellationToken)
   at Customer.Client.Controllers.PaymentController.Index() in D:\SourceGitHub\CustomerAPI\Customer.Client\Controllers\PaymentController.cs:line 22
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
-------------------------------------------------------------------------------------------------------------
I am working on API project having Controller ->service layer-> Repository but getting the above error,
i have setup cosmosdb connection using overload in startup file (also tried using appsetting.development.json)
Still issue is not getting resolve
My model is as below:- 
namespace Customer.Domain.Entities
{
    [PartitionKeyPath("/dType")]
    public class Payment : Item
    {        
        public string uId { get; set; }
        [JsonProperty("dType")]
        public string dType { get;} = $"ap-payment";
        public string accountUId { get; set; }
        public string contractUId { get; set; }
        public int billCycleNumber { get; set; }        
        public DateTime date { get; set; }
        public string gclPaymentId { get; set; }
        public string description { get; set; }
        public string status { get; set; }
        public string referenece { get; set; }
        public DateTime createdOn { get; set; }
        public DateTime updatedOn { get; set; }

        protected override string GetPartitionKeyValue() => dType;
    }
}

**Comment by IEvangelist** [comment]
Yikes, this a bit unexpected. There was a recent change to include the ability to have a unique key policy for the container - I'll fix this right away.
